// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDROHxCejWFJUO47VHYPGlhs3RoPqlFT8w',
    appId: '1:1083783927025:web:8b8a8191305e81b62b8550',
    messagingSenderId: '1083783927025',
    projectId: 'unilinkdemo-771b8',
    authDomain: 'unilinkdemo-771b8.firebaseapp.com',
    storageBucket: 'unilinkdemo-771b8.firebasestorage.app',
    measurementId: 'G-7JTB0FYHFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxNR8_uCfhXKt_GHXADgqdHfPs9Dv27Cg',
    appId: '1:1083783927025:android:207b917248a8987d2b8550',
    messagingSenderId: '1083783927025',
    projectId: 'unilinkdemo-771b8',
    storageBucket: 'unilinkdemo-771b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeuupBjZ4SrlF1-PyKoblLIfyUi4ajEbI',
    appId: '1:1083783927025:ios:372b60c2b8d3b4b42b8550',
    messagingSenderId: '1083783927025',
    projectId: 'unilinkdemo-771b8',
    storageBucket: 'unilinkdemo-771b8.firebasestorage.app',
    iosBundleId: 'com.example.uniLinkDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeuupBjZ4SrlF1-PyKoblLIfyUi4ajEbI',
    appId: '1:1083783927025:ios:372b60c2b8d3b4b42b8550',
    messagingSenderId: '1083783927025',
    projectId: 'unilinkdemo-771b8',
    storageBucket: 'unilinkdemo-771b8.firebasestorage.app',
    iosBundleId: 'com.example.uniLinkDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDROHxCejWFJUO47VHYPGlhs3RoPqlFT8w',
    appId: '1:1083783927025:web:d218367c0d7a000c2b8550',
    messagingSenderId: '1083783927025',
    projectId: 'unilinkdemo-771b8',
    authDomain: 'unilinkdemo-771b8.firebaseapp.com',
    storageBucket: 'unilinkdemo-771b8.firebasestorage.app',
    measurementId: 'G-8G9896WMLT',
  );
}
